architect:
  - dgroup
assets:
  .pypirc: dgroup/home#.pypirc
#install: |
#  export GEM_HOME=~/.ruby
#  export GEM_PATH=$GEM_HOME:$GEM_PATH
docker:
  image: python:3.8.5
release:
  script: |-
    set -e
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    make test
    sed -i "s/0\.0\.0/${tag}/g" g2w/VERSION
    sed -i "s/0\.0\.0/${tag}/g" setup.py
    sed -i "s/0\.0\.0/${tag}/g" .github/workflows/master.yml
    python -m pip install --upgrade pip
    pip install setuptools wheel twine
    python setup.py sdist bdist_wheel
    git add g2w/VERSION setup.py .github/workflows/master.yml
    git commit -m "version set to ${tag}"
    twine --config-file=../.pypirc upload dist/*

# @todo #/DEV Activate linting process during release flake8, black, mypy

# @todo #/DEV Invoke from rultor the docker build&push process through the Github actions

#    curl -s -X POST --url "https://circleci.com/api/v2/project/gh/dgroup/lazylead/envvar" -H @../circleci.header -H "accept: application/json" -H "content-type: application/json" -d "{ \"name\": \"DOCKER_RELEASE_TAGS\", \"value\": \"${tag}\" }" -o /dev/null
#    curl -s -X POST --url https://circleci.com/api/v2/project/gh/dgroup/lazylead/pipeline -H @../circleci.header -H 'accept: application/json' -H 'content-type: application/json' -H 'x-attribution-login: dgroup' -o /dev/null
merge:
  squash: true
  script: |-
    make install
    make lint
    make test