version: "3.9"
services:
  g2ws:
    image: dgroup/g2w:latest
    container_name: g2w
    environment:
      WS_URL_ALL_USERS: "https://xxx.worksection.com/xxxx"
      WS_URL_POST_COMMENT: "https://xxx.worksection.com/xxxx"
      WS_EMAIL: "xxx.worksection.bot@gmail.com"
      WS_ADMIN_USER_ID: "370080"
    build:
      dockerfile: Containerfile
      context: .
    ports:
      - "8080:8080"
    restart: always
